---
- hosts: all
  sudo: yes
  vars:
# the following create a default non-privileged user
    - weakuser: xsce-admin
    - weakpw: 12admin
  roles:
#      - { role: makez, tags: ['makez'] }
#      - { role: mkoffline, tags: ['mkoffline'] }
      - { role: access, tags: ['access'] }
      - { role: vnc, tags: ['vnc'] }
#      - { role: openvpn, tags: ['openvpn'] }
#      - { role: 3g, tags: ['3g'] }
