---
- hosts: all
  sudo: yes
  vars:
    - weakuser: setup
    - weakpw: 12setup
  roles:
      - { role: makez, tags: ['makez'] }
      - { role: access, tags: ['access'] }
      - { role: vnc, tags: ['vnc'] }
      - { role: openvpn, tags: ['openvpn'] }
      - { role: 3g, tags: ['3g'] }
