- name: Install textmode remote access packages
  yum: name={{ item }}
       state=present
  with_items:
        - screen
        - lynx

- name: Create a non privleged user 
  user: name={{ weakuser }}
        generate_ssh_key=yes

- name: Add a password for this user
  shell: "echo {{ weakpw }} | /bin/passwd {{ weakuser }} --stdin" 

- name:  Cause the user password to expire at first logon
  shell: chage -d 0  {{ weakuser }}

