- name: Install openvpn packages
  yum: name=${item}
       state=installed
  with_items:
       openvpn

- name: Configure openvpn
  template: backup=yes
            src=${item.src}
            dest=${item.dest}
            owner=${item.owner}
            group=root
            mode=${item.mode}
  with_items:
    - { src: 'ca.crt', dest: '/etc/openvpn', owner: "root" , mode: '0644' }
    - { src: 'client1.crt', dest: '/etc/openvpn', owner: "root" , mode: '0644' }
    - { src: 'client1.key', dest: '/etc/openvpn', owner: "root" , mode: '0600' }
    - { src: 'roadwarrior-client.conf', dest: '/etc/openvpn', owner: "root" , mode: '0644' }
